import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("myPortfolio/withChair.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    /* highlight-line */
    actions["Armature|mixamo.com|Layer0"].play();
    /* highlight-line */
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
         {/* <directionalLight
          position={[1, 2, 0]}
          intensity={1}
          castShadow
          shadow-mapSize-width={2000}
          shadow-mapSize-height={2000}
          shadow-camera-far={2000}
          shadow-camera-left={-100}
          shadow-camera-right={100}
          shadow-camera-top={100}
          shadow-camera-bottom={-100}
          color={"#ffffff"}
        /> */}
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          castShadow={true}
          receiveShadow={true}
        >

          <group
            name="ea16bd4ed87b40cb88f597328f8e0c75fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
            castShadow={true}
            receiveShadow={true}
          >
            <group name="RootNode">
              <group name="*GAMEREADY" rotation={[-Math.PI / 2, 0, 0]}>
                <group name="TEXSET_A">
                  <group name="ARMCHAIR" rotation={[0, 0, 0.19]}>
                    <mesh
                      name="ARMCHAIR_TEXSET_A_0"
                      geometry={nodes.ARMCHAIR_TEXSET_A_0.geometry}
                      material={materials.TEXSET_A}
                      castShadow={true}
                      receiveShadow={true}
                    />
                  </group>

                  <group
                    name="COFFEETABLE"
                    position={[23.31, -100.42, 0]}
                    rotation={[0, 0, 0.07]}
                    castShadow={true}
                    receiveShadow={true}
                  />
                  <group
                    name="FLOORLAMP"
                    position={[80.27, 19.27, 138.46]}
                    rotation={[-0.02, 0.05, 0.69]}
                    scale={1.03}
                    castShadow={true}
                    receiveShadow={true}
                  >
                    <group
                      name="Object_6_1"
                      position={[0, 0, -10.32]}
                      castShadow={true}
                      receiveShadow={true}
                    >
                      <mesh
                        name="FLOORLAMP_TEXSET_A_0"
                        geometry={nodes.FLOORLAMP_TEXSET_A_0.geometry}
                        material={materials.TEXSET_A}
                        castShadow={true}
                        receiveShadow={true}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group
          name="Sketchfab_model001"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.02}
          castShadow={true}
          receiveShadow={true}
        >
          <group
            name="carpetlowobjcleanermaterialmergergles"
            castShadow={true}
            receiveShadow={true}
          >
            <mesh
              name="Object_10"
              geometry={nodes.Object_10.geometry}
              material={materials.Material__3}
              castShadow={true}
              receiveShadow={true}
            />
            <mesh
              name="Object_11"
              geometry={nodes.Object_11.geometry}
              material={materials.Material__3}
              castShadow={true}
              receiveShadow={true}
            />
            <mesh
              name="Object_12"
              geometry={nodes.Object_12.geometry}
              material={materials.Material__3}
              castShadow={true}
              receiveShadow={true}
            />
            <mesh
              name="Object_13"
              geometry={nodes.Object_13.geometry}
              material={materials.Material__3}
              castShadow={true}
              receiveShadow={true}
            />
            <mesh
              name="Object_14"
              geometry={nodes.Object_14.geometry}
              material={materials.Material__3}
              castShadow={true}
              receiveShadow={true}
            />
            <mesh
              name="Object_15"
              geometry={nodes.Object_15.geometry}
              material={materials.Material__3}
              castShadow={true}
              receiveShadow={true}
            />
            <mesh
              name="Object_16"
              geometry={nodes.Object_16.geometry}
              material={materials.Material__3}
              castShadow={true}
              receiveShadow={true}
            />
            <mesh
              name="Object_17"
              geometry={nodes.Object_17.geometry}
              material={materials.Material__3}
              castShadow={true}
              receiveShadow={true}
            />
            <mesh
              name="Object_18"
              geometry={nodes.Object_18.geometry}
              material={materials.Material__3}
              castShadow={true}
              receiveShadow={true}
            />
            <mesh
              name="Object_19"
              geometry={nodes.Object_19.geometry}
              material={materials.Material__3}
              castShadow={true}
              receiveShadow={true}
            />
            <mesh
              name="Object_2"
              geometry={nodes.Object_2.geometry}
              material={materials.Material__2}
              castShadow={true}
              receiveShadow={true}
            />
            <mesh
              name="Object_20"
              geometry={nodes.Object_20.geometry}
              material={materials.Material__3}
              castShadow={true}
              receiveShadow={true}
            />
            <mesh
              name="Object_21"
              geometry={nodes.Object_21.geometry}
              material={materials.Material__3}
              castShadow={true}
              receiveShadow={true}
            />
            <mesh
              name="Object_22"
              geometry={nodes.Object_22.geometry}
              material={materials.Material__3}
              castShadow={true}
              receiveShadow={true}
            />
            <mesh
              name="Object_23"
              geometry={nodes.Object_23.geometry}
              material={materials.Material__3}
              castShadow={true}
              receiveShadow={true}
            />
            <mesh
              name="Object_24"
              geometry={nodes.Object_24.geometry}
              material={materials.Material__3}
              castShadow={true}
              receiveShadow={true}
            />
            <mesh
              name="Object_25"
              geometry={nodes.Object_25.geometry}
              material={materials.Material__3}
              castShadow={true}
              receiveShadow={true}
            />
            <mesh
              name="Object_26"
              geometry={nodes.Object_26.geometry}
              material={materials.Material__3}
              castShadow={true}
              receiveShadow={true}
            />
            <mesh
              name="Object_27"
              geometry={nodes.Object_27.geometry}
              material={materials.Material__3}
              castShadow={true}
              receiveShadow={true}
            />
            <mesh
              name="Object_28"
              geometry={nodes.Object_28.geometry}
              material={materials.Material__3}
              castShadow={true}
              receiveShadow={true}
            />
            <mesh
              name="Object_3"
              geometry={nodes.Object_3.geometry}
              material={materials.Material__3}
              castShadow={true}
              receiveShadow={true}
            />
            <mesh
              name="Object_4"
              geometry={nodes.Object_4.geometry}
              material={materials.Material__3}
              castShadow={true}
              receiveShadow={true}
            />
            <mesh
              name="Object_5"
              geometry={nodes.Object_5.geometry}
              material={materials.Material__3}
              castShadow={true}
              receiveShadow={true}
            />
            <mesh
              name="Object_6001"
              geometry={nodes.Object_6001.geometry}
              material={materials.Material__3}
              castShadow={true}
              receiveShadow={true}
            />
            <mesh
              name="Object_7"
              geometry={nodes.Object_7.geometry}
              material={materials.Material__3}
              castShadow={true}
              receiveShadow={true}
            />
            <mesh
              name="Object_8"
              geometry={nodes.Object_8.geometry}
              material={materials.Material__3}
              castShadow={true}
              receiveShadow={true}
            />
            <mesh
              name="Object_9"
              geometry={nodes.Object_9.geometry}
              material={materials.Material__3}
              castShadow={true}
              receiveShadow={true}
            />
          </group>
        </group>
        <group name="Armature">
          <primitive object={nodes.Hips} />
          <skinnedMesh
            name="Wolf3D_Body"
            geometry={nodes.Wolf3D_Body.geometry}
            material={materials.Wolf3D_Body}
            skeleton={nodes.Wolf3D_Body.skeleton}
            castShadow={true}
            receiveShadow={true}
          />
          <skinnedMesh
            name="Wolf3D_Hair"
            geometry={nodes.Wolf3D_Hair.geometry}
            material={materials.Wolf3D_Hair}
            skeleton={nodes.Wolf3D_Hair.skeleton}
            castShadow={true}
            receiveShadow={true}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Bottom"
            geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
            material={materials.Wolf3D_Outfit_Bottom}
            skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
            castShadow={true}
            receiveShadow={true}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Footwear"
            geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
            material={materials.Wolf3D_Outfit_Footwear}
            skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
            castShadow={true}
            receiveShadow={true}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Top"
            geometry={nodes.Wolf3D_Outfit_Top.geometry}
            material={materials.Wolf3D_Outfit_Top}
            skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
            castShadow={true}
            receiveShadow={true}
          />
          <skinnedMesh
            name="EyeLeft"
            geometry={nodes.EyeLeft.geometry}
            material={materials.Wolf3D_Eye}
            skeleton={nodes.EyeLeft.skeleton}
            morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
            morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
            castShadow={true}
            receiveShadow={true}
          />
          <skinnedMesh
            name="EyeRight"
            geometry={nodes.EyeRight.geometry}
            material={materials.Wolf3D_Eye}
            skeleton={nodes.EyeRight.skeleton}
            morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
            morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
            castShadow={true}
            receiveShadow={true}
          />
          <skinnedMesh
            name="Wolf3D_Head"
            geometry={nodes.Wolf3D_Head.geometry}
            material={materials.Wolf3D_Skin}
            skeleton={nodes.Wolf3D_Head.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
            castShadow={true}
            receiveShadow={true}
          />
          <skinnedMesh
            name="Wolf3D_Teeth"
            geometry={nodes.Wolf3D_Teeth.geometry}
            material={materials.Wolf3D_Teeth}
            skeleton={nodes.Wolf3D_Teeth.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
            castShadow={true}
            receiveShadow={true}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("myPortfolio/withChair.glb");
